#!/usr/bin/env python3
"""Keep the generated front pages from being hand-edited, and say where to edit instead.

Every language wiki's front page is generated by `tools/build_main_pages.py`
from a shared template. A hand edit on one of them is a dead end: it reaches
only that language, and the next `push` overwrites it. On 2026-08-01 that
happened for real - the English gallery lost a photo on-wiki and the other 33
wikis never heard about it.

So each front page gets:

  * sysop-only edit/move protection, with a protection reason pointing at
    `Hitchwiki:Main page` (that reason is what a logged-in non-admin sees on
    the "View source" screen);
  * a `MediaWiki:Editnotice-0-<DBkey>` shown above the edit box, for the
    admins who *can* still edit it, naming the file to change instead and
    the two on-wiki templates that do update the whole family.

Run `tools/build_main_pages.py check` afterwards (weekly cron) to catch an
admin who edits one anyway.

Usage:
    python3 tools/protect_main_pages.py notices [<lang>]   # write the edit notices
    python3 tools/protect_main_pages.py protect [<lang>]   # sysop-protect the pages
    python3 tools/protect_main_pages.py status  [<lang>]   # show protection per wiki
"""

import argparse
import json
import subprocess
import sys

from build_main_pages import CONTAINER, TEMPLATED_LANGUAGES, get_main_page_title

DOC_PAGE = "Hitchwiki:Main page"
PROTECT_REASON = (
    "Generated from the shared front-page template - see "
    "[[:en:Hitchwiki:Main page]] for where to make changes instead"
)

NOTICE = """<div style="border: 1px solid #fc3; background: #fef6e7; padding: 0.8em 1em; margin-bottom: 1em;">
'''This front page is generated from a template shared by all 34 Hitchwiki language wikis. Please do not edit it here.'''

An edit made on this page reaches only this one language, and is overwritten the next time the front pages are regenerated. See '''[[{doc}|{doc_label}]]''' for where to make the change instead:

* the '''Events''' and '''News''' boxes are edited at [[{events}|Template:EventsShared]] and [[{news}|Template:NewsShared]] on the English wiki, and update every language wiki immediately - no admin needed;
* the '''layout''' lives in <code>tools/main_page_template.wikitext</code> in the [https://github.com/Hitchwiki/hitchwiki.org hitchwiki.org repository];
* this language's '''wording''' lives in <code>tools/main_page_i18n/{lang}.json</code> there.
</div>"""


def run(args, **kwargs):
    return subprocess.run(args, capture_output=True, text=True, check=True, **kwargs)


def notice_title(lang):
    """MediaWiki:Editnotice-0-<DBkey>, per Title::getEditNotices()."""
    dbkey = get_main_page_title(lang).replace(" ", "_").replace("/", "-")
    return f"MediaWiki:Editnotice-0-{dbkey}"


def notice_text(lang):
    # On the English wiki the pages are local; elsewhere point across the interwiki.
    prefix = "" if lang == "en" else ":en:"
    return NOTICE.format(
        doc=f"{prefix}{DOC_PAGE}",
        doc_label=DOC_PAGE,
        events=f"{prefix}Template:EventsShared",
        news=f"{prefix}Template:NewsShared",
        lang=lang,
    )


def cmd_notices(languages):
    for lang in languages:
        title = notice_title(lang)
        subprocess.run(
            [
                "docker", "exec", "-i", CONTAINER, "php",
                "/var/www/html/maintenance/edit.php", f"--wiki={lang}", "--bot",
                "--summary", "Front page is generated from a shared template; "
                             "point editors at Hitchwiki:Main page",
                title,
            ],
            input=notice_text(lang), text=True, check=True,
        )
        print(f"{lang}: wrote {title}")
    return 0


def cmd_protect(languages):
    for lang in languages:
        title = get_main_page_title(lang)
        run([
            "docker", "exec", CONTAINER, "php",
            "/var/www/html/maintenance/run.php", "protect", f"--wiki={lang}",
            "--reason", PROTECT_REASON, title,
        ])
        print(f"{lang}: protected {title!r} (sysop)")
    return 0


def cmd_status(languages):
    bad = 0
    for lang in languages:
        title = get_main_page_title(lang)
        out = run([
            "docker", "exec", CONTAINER, "curl", "-s",
            f"http://localhost/{lang}/api.php?action=query&prop=info&inprop=protection"
            f"&titles={title.replace(' ', '%20')}&format=json",
        ]).stdout
        page = next(iter(json.loads(out)["query"]["pages"].values()))
        levels = {p["type"]: p["level"] for p in page.get("protection", [])}
        ok = levels.get("edit") == "sysop"
        bad += not ok
        print(f"{lang:>3}  {title:<24} edit={levels.get('edit', '-'):<8} "
              f"move={levels.get('move', '-'):<8} {'ok' if ok else 'UNPROTECTED'}")
    return 1 if bad else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for name, help_text in (
        ("notices", "write MediaWiki:Editnotice-0-<page> on each wiki"),
        ("protect", "sysop-protect each front page"),
        ("status", "show current protection of each front page"),
    ):
        p = sub.add_parser(name, help=help_text)
        p.add_argument("lang", nargs="?", default="all",
                       help="language code, or 'all' (default)")

    args = parser.parse_args()
    languages = TEMPLATED_LANGUAGES if args.lang == "all" else [args.lang]
    return {
        "notices": cmd_notices,
        "protect": cmd_protect,
        "status": cmd_status,
    }[args.command](languages)


if __name__ == "__main__":
    sys.exit(main())
